In [4]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/yelp-dataset/Dataset_User_Agreement.pdf
/kaggle/input/yelp-dataset/yelp_academic_dataset_review.json
/kaggle/input/yelp-dataset/yelp_academic_dataset_checkin.json
/kaggle/input/yelp-dataset/yelp_academic_dataset_business.json
/kaggle/input/yelp-dataset/yelp_academic_dataset_tip.json
/kaggle/input/yelp-dataset/yelp_academic_dataset_user.json

In [5]:
import pandas as pd
import json

# Load JSON into a DataFrame
def load_json_file(filepath):
    data = []
    with open(filepath, 'r') as f:
        for line in f:
            data.append(json.loads(line))
    return pd.DataFrame(data)

business_df = load_json_file('/kaggle/input/yelp-dataset/yelp_academic_dataset_business.json')
print(f"Loaded {len(business_df)} business records")
business_df.head()

Loaded 150346 business records

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,CA,93101,34.426679,-119.711197,5.0,7,0,{'ByAppointmentOnly': 'True'},"Doctors, Traditional Chinese Medicine, Naturop...",None
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,38.551126,-90.335695,3.0,15,1,{'BusinessAcceptsCreditCards': 'True'},"Shipping Centers, Local Services, Notaries, Ma...","{'Monday': '0:0-0:0', 'Tuesday': '8:0-18:30', ..."
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,AZ,85711,32.223236,-110.880452,3.5,22,0,"{'BikeParking': 'True', 'BusinessAcceptsCredit...","Department Stores, Shopping, Fashion, Home & G...","{'Monday': '8:0-22:0', 'Tuesday': '8:0-22:0', ..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,PA,18054,40.338183,-75.471659,4.5,13,1,"{'BusinessAcceptsCreditCards': 'True', 'Wheelc...","Brewpubs, Breweries, Food","{'Wednesday': '14:0-22:0', 'Thursday': '16:0-2..."

In [6]:
# Show basic info
print("BUSINESS DATA STRUCTURE:")
print(business_df.info())

# Show column names
print("\nCOLUMNS AVAILABLE:")
print(business_df.columns.tolist())

# Check for nested JSON columns
print("\nNESTED COLUMNS INSPECTION:")
print("Attributes type:", type(business_df['attributes'].iloc[0]))
print("Hours type:", type(business_df['hours'].iloc[0]))

BUSINESS DATA STRUCTURE:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150346 entries, 0 to 150345
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   business_id   150346 non-null  object
 1   name          150346 non-null  object
 2   address       150346 non-null  object
 3   city          150346 non-null  object
 4   state         150346 non-null  object
 5   postal_code   150346 non-null  object
 6   latitude      150346 non-null  float64
 7   longitude     150346 non-null  float64
 8   stars         150346 non-null  float64
 9   review_count  150346 non-null  int64
 10  is_open       150346 non-null  int64
 11  attributes    136602 non-null  object
 12  categories    150243 non-null  object
 13  hours         127123 non-null  object
dtypes: float64(3), int64(2), object(9)
memory usage: 16.1+ MB
None

COLUMNS AVAILABLE:
['business_id', 'name', 'address', 'city', 'state', 'postal_code', 'latitude', 'longitude', 'stars', 'review_count', 'is_open', 'attributes', 'categories', 'hours']

NESTED COLUMNS INSPECTION:
Attributes type: <class 'dict'>
Hours type: <class 'NoneType'>

In [7]:
# Check for nulls
business_df.isnull().sum()

business_id         0
name                0
address             0
city                0
state               0
postal_code         0
latitude            0
longitude           0
stars               0
review_count        0
is_open             0
attributes      13744
categories        103
hours           23223
dtype: int64

In [8]:
# Numeric stats
business_df.describe()

,latitude,longitude,stars,review_count,is_open
count,150346.000000,150346.000000,150346.000000,150346.000000,150346.00000
mean,36.671150,-89.357339,3.596724,44.866561,0.79615
std,5.872759,14.918502,0.974421,121.120136,0.40286
min,27.555127,-120.095137,1.000000,5.000000,0.00000
25%,32.187293,-90.357810,3.000000,8.000000,1.00000
50%,38.777413,-86.121179,3.500000,15.000000,1.00000
75%,39.954036,-75.421542,4.500000,37.000000,1.00000
max,53.679197,-73.200457,5.000000,7568.000000,1.00000

In [9]:
import pandas as pd
import json
import numpy as np

# Function to safely convert string to dict
def safe_json_loads(x):
    if pd.isna(x) or x == '':
        return {}
    try:
        return json.loads(x.replace("'", "\"")) if isinstance(x, str) else x
    except:
        return {}

# Clean the business data
def clean_business_data(df):
    # Convert string representations of dictionaries to actual dicts
    df['attributes'] = df['attributes'].apply(safe_json_loads)
    df['hours'] = df['hours'].apply(safe_json_loads)
    
    # Convert categories from string to list
    df['categories'] = df['categories'].str.split(', ').fillna('').apply(lambda x: [c.strip() for c in x] if x else [])
    
    return df

business_df = clean_business_data(business_df)

In [10]:
# Expand attributes into separate columns
def expand_attributes(df):
    # Get all unique attribute keys
    all_attrs = set()
    for attrs in df['attributes']:
        all_attrs.update(attrs.keys())
    
    # Create columns for each attribute
    for attr in all_attrs:
        df[f"attr_{attr}"] = df['attributes'].apply(lambda x: x.get(attr, np.nan))
    
    # Drop the original attributes column
    df = df.drop('attributes', axis=1)
    return df

business_df = expand_attributes(business_df)

In [11]:
# Expand hours into separate columns
def expand_hours(df):
    days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
    
    for day in days:
        df[f"hours_{day}"] = df['hours'].apply(lambda x: x.get(day, np.nan))
    
    # Optionally split hours into open/close times
    for day in days:
        df[[f"hours_{day}_open", f"hours_{day}_close"]] = df[f"hours_{day}"].str.split('-', expand=True)
        df = df.drop(f"hours_{day}", axis=1)
    
    df = df.drop('hours', axis=1)
    return df

business_df = expand_hours(business_df)

In [9]:
# # Option 1: Keep as comma-separated string (simpler for SQL)
# business_df['categories'] = business_df['categories'].apply(lambda x: ', '.join(x) if x else '')

# # Option 2: Create a separate categories table (better normalized)
# # This would be a second table with business_id and category columns

In [12]:
# Convert boolean-like strings to actual booleans
bool_cols = [col for col in business_df.columns if col.startswith('attr_') and business_df[col].isin(['True', 'False']).any()]
for col in bool_cols:
    business_df[col] = business_df[col].map({'True': True, 'False': False})

# Convert numeric columns
numeric_cols = ['latitude', 'longitude', 'stars', 'review_count', 'is_open']
business_df[numeric_cols] = business_df[numeric_cols].apply(pd.to_numeric, errors='coerce')

# Clean text columns
text_cols = ['city', 'state', 'postal_code']
business_df[text_cols] = business_df[text_cols].apply(lambda x: x.str.strip())

In [13]:
print("\nData Summary:")
print(business_df.info())

# print("\nDescriptive Statistics:")
# print(business_df.describe(include='all'))

Data Summary:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150346 entries, 0 to 150345
Data columns (total 65 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   business_id                      150346 non-null  object
 1   name                             150346 non-null  object
 2   address                          150346 non-null  object
 3   city                             150346 non-null  object
 4   state                            150346 non-null  object
 5   postal_code                      150346 non-null  object
 6   latitude                         150346 non-null  float64
 7   longitude                        150346 non-null  float64
 8   stars                            150346 non-null  float64
 9   review_count                     150346 non-null  int64
 10  is_open                          150346 non-null  int64
 11  categories                       150346 non-null  object
 12  attr_RestaurantsGoodForGroups    44149 non-null   object
 13  attr_BusinessAcceptsCreditCards  119692 non-null  object
 14  attr_HappyHour                   15169 non-null   object
 15  attr_DogsAllowed                 18258 non-null   object
 16  attr_BestNights                  5694 non-null    object
 17  attr_RestaurantsPriceRange2      85314 non-null   object
 18  attr_BusinessParking             91085 non-null   object
 19  attr_RestaurantsAttire           39255 non-null   object
 20  attr_BusinessAcceptsBitcoin      17427 non-null   object
 21  attr_Smoking                     4567 non-null    object
 22  attr_WheelchairAccessible        28926 non-null   object
 23  attr_NoiseLevel                  37993 non-null   object
 24  attr_Alcohol                     43189 non-null   object
 25  attr_GoodForKids                 53347 non-null   object
 26  attr_GoodForMeal                 29087 non-null   object
 27  attr_AgesAllowed                 129 non-null     object
 28  attr_DietaryRestrictions         31 non-null      object
 29  attr_RestaurantsReservations     44959 non-null   object
 30  attr_OutdoorSeating              46920 non-null   object
 31  attr_Open24Hours                 39 non-null      object
 32  attr_ByAppointmentOnly           42299 non-null   object
 33  attr_BYOBCorkage                 1444 non-null    object
 34  attr_DriveThru                   7005 non-null    object
 35  attr_CoatCheck                   5580 non-null    object
 36  attr_Caters                      40067 non-null   object
 37  attr_BYOB                        4439 non-null    object
 38  attr_GoodForDancing              4628 non-null    object
 39  attr_WiFi                        56914 non-null   object
 40  attr_Corkage                     3542 non-null    object
 41  attr_BikeParking                 72558 non-null   object
 42  attr_RestaurantsTableService     19967 non-null   object
 43  attr_Music                       7521 non-null    object
 44  attr_RestaurantsDelivery         52334 non-null   object
 45  attr_HairSpecializesIn           1065 non-null    object
 46  attr_AcceptsInsurance            5705 non-null    object
 47  attr_HasTV                       45065 non-null   object
 48  attr_RestaurantsTakeOut          57752 non-null   object
 49  attr_Ambience                    44279 non-null   object
 50  attr_RestaurantsCounterService   19 non-null      object
 51  hours_Monday_open                114474 non-null  object
 52  hours_Monday_close               114474 non-null  object
 53  hours_Tuesday_open               120631 non-null  object
 54  hours_Tuesday_close              120631 non-null  object
 55  hours_Wednesday_open             123771 non-null  object
 56  hours_Wednesday_close            123771 non-null  object
 57  hours_Thursday_open              125198 non-null  object
 58  hours_Thursday_close             125198 non-null  object
 59  hours_Friday_open                124999 non-null  object
 60  hours_Friday_close               124999 non-null  object
 61  hours_Saturday_open              110770 non-null  object
 62  hours_Saturday_close             110770 non-null  object
 63  hours_Sunday_open                81172 non-null   object
 64  hours_Sunday_close               81172 non-null   object
dtypes: float64(3), int64(2), object(60)
memory usage: 74.6+ MB
None

In [14]:
business_df.head()

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,...,hours_Wednesday_open,hours_Wednesday_close,hours_Thursday_open,hours_Thursday_close,hours_Friday_open,hours_Friday_close,hours_Saturday_open,hours_Saturday_close,hours_Sunday_open,hours_Sunday_close
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,CA,93101,34.426679,-119.711197,5.0,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,38.551126,-90.335695,3.0,15,...,8:0,18:30,8:0,18:30,8:0,18:30,8:0,14:0,NaN,NaN
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,AZ,85711,32.223236,-110.880452,3.5,22,...,8:0,22:0,8:0,22:0,8:0,23:0,8:0,23:0,8:0,22:0
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,...,7:0,20:0,7:0,20:0,7:0,21:0,7:0,21:0,7:0,21:0
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,PA,18054,40.338183,-75.471659,4.5,13,...,14:0,22:0,16:0,22:0,12:0,22:0,12:0,22:0,12:0,18:0

In [15]:
# Display just the categories column
print("=== Categories Column (First 10 Rows) ===")
print(business_df['categories'].head(10))

=== Categories Column (First 10 Rows) ===
0    [Doctors, Traditional Chinese Medicine, Naturo...
1    [Shipping Centers, Local Services, Notaries, M...
2    [Department Stores, Shopping, Fashion, Home & ...
3    [Restaurants, Food, Bubble Tea, Coffee & Tea, ...
4                          [Brewpubs, Breweries, Food]
5    [Burgers, Fast Food, Sandwiches, Food, Ice Cre...
6    [Sporting Goods, Fashion, Shoe Stores, Shoppin...
7                [Synagogues, Religious Organizations]
8    [Pubs, Restaurants, Italian, Bars, American (T...
9    [Ice Cream & Frozen Yogurt, Fast Food, Burgers...
Name: categories, dtype: object

In [16]:
# Create cleaned version excluding only the categories column
business_clean = business_df.drop(columns=['categories']).copy()

# Verify the result
print("Columns in business_clean:", business_clean.columns.tolist())
business_clean.head()

Columns in business_clean: ['business_id', 'name', 'address', 'city', 'state', 'postal_code', 'latitude', 'longitude', 'stars', 'review_count', 'is_open', 'attr_RestaurantsGoodForGroups', 'attr_BusinessAcceptsCreditCards', 'attr_HappyHour', 'attr_DogsAllowed', 'attr_BestNights', 'attr_RestaurantsPriceRange2', 'attr_BusinessParking', 'attr_RestaurantsAttire', 'attr_BusinessAcceptsBitcoin', 'attr_Smoking', 'attr_WheelchairAccessible', 'attr_NoiseLevel', 'attr_Alcohol', 'attr_GoodForKids', 'attr_GoodForMeal', 'attr_AgesAllowed', 'attr_DietaryRestrictions', 'attr_RestaurantsReservations', 'attr_OutdoorSeating', 'attr_Open24Hours', 'attr_ByAppointmentOnly', 'attr_BYOBCorkage', 'attr_DriveThru', 'attr_CoatCheck', 'attr_Caters', 'attr_BYOB', 'attr_GoodForDancing', 'attr_WiFi', 'attr_Corkage', 'attr_BikeParking', 'attr_RestaurantsTableService', 'attr_Music', 'attr_RestaurantsDelivery', 'attr_HairSpecializesIn', 'attr_AcceptsInsurance', 'attr_HasTV', 'attr_RestaurantsTakeOut', 'attr_Ambience', 'attr_RestaurantsCounterService', 'hours_Monday_open', 'hours_Monday_close', 'hours_Tuesday_open', 'hours_Tuesday_close', 'hours_Wednesday_open', 'hours_Wednesday_close', 'hours_Thursday_open', 'hours_Thursday_close', 'hours_Friday_open', 'hours_Friday_close', 'hours_Saturday_open', 'hours_Saturday_close', 'hours_Sunday_open', 'hours_Sunday_close']

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,...,hours_Wednesday_open,hours_Wednesday_close,hours_Thursday_open,hours_Thursday_close,hours_Friday_open,hours_Friday_close,hours_Saturday_open,hours_Saturday_close,hours_Sunday_open,hours_Sunday_close
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,CA,93101,34.426679,-119.711197,5.0,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,38.551126,-90.335695,3.0,15,...,8:0,18:30,8:0,18:30,8:0,18:30,8:0,14:0,NaN,NaN
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,AZ,85711,32.223236,-110.880452,3.5,22,...,8:0,22:0,8:0,22:0,8:0,23:0,8:0,23:0,8:0,22:0
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,...,7:0,20:0,7:0,20:0,7:0,21:0,7:0,21:0,7:0,21:0
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,PA,18054,40.338183,-75.471659,4.5,13,...,14:0,22:0,16:0,22:0,12:0,22:0,12:0,22:0,12:0,18:0

In [17]:
# Explode categories into a separate table
business_categories = business_df[['business_id', 'categories']].dropna().copy()
business_categories['categories'] = business_categories['categories'].str.split(', ')

# Explode into rows
business_categories = business_categories.explode('categories').reset_index(drop=True)
business_categories.rename(columns={'categories': 'category'}, inplace=True)

# Preview
business_categories.head()

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

              business_id  category
0  Pns2l4eNsfO8kk83dixA6A       NaN
1  mpf3x-BjTdTEA3yCZrAYPw       NaN
2  tUFrWirKiKi_TAnsVWINQQ       NaN
3  MTSW4McQd7CbVtyjqoe9mw       NaN
4  mWMc6_wTdE0EUBKIGXDVfA       NaN

In [16]:
# def flatten_json_columns(df, column_names):
#     """Flatten nested JSON columns into separate columns"""
#     for col in column_names:
#         if col in df.columns:
#             # Handle null values
#             df[col] = df[col].apply(lambda x: x if isinstance(x, dict) else {})
#             flattened = json_normalize(df[col])
#             flattened.columns = [f"{col}_{subcol}" for subcol in flattened.columns]
#             df = pd.concat([df.drop(col, axis=1), flattened], axis=1)
#     return df

# # Flatten attributes and hours
# business_df = flatten_json_columns(business_df, ['attributes', 'hours'])
# print("\nFLATTENED COLUMNS:")
# print(business_df.columns.tolist())

In [17]:
# # Handle categories (which is a list of strings)
# business_df['categories'] = business_df['categories'].apply(lambda x: ', '.join(x) if isinstance(x, list) else '')

# # Convert boolean columns to 1/0
# bool_cols = business_df.select_dtypes(include=['bool']).columns
# business_df[bool_cols] = business_df[bool_cols].astype(int)

# # Convert all text columns to string and limit length
# text_cols = business_df.select_dtypes(include=['object']).columns
# business_df[text_cols] = business_df[text_cols].astype(str).apply(lambda x: x.str[:255])

# # Show cleaned data
# business_df.head()

In [18]:
import pandas as pd
import json

# Load check-in data
def load_json_file(filepath):
    data = []
    with open(filepath, 'r') as f:
        for line in f:
            data.append(json.loads(line))
    return pd.DataFrame(data)

checkin_df = load_json_file('/kaggle/input/yelp-dataset/yelp_academic_dataset_checkin.json')
print(f"Loaded {len(checkin_df)} check-in records")
checkin_df.head()

Loaded 131930 check-in records

              business_id                                               date
0  ---kPU91CF4Lq2-WlRu9Lw  2020-03-13 21:10:56, 2020-06-02 22:18:06, 2020...
1  --0iUa4sNDFiZFrAdIWhZQ  2010-09-13 21:43:09, 2011-05-04 23:08:15, 2011...
2  --30_8IhuyMHbSOcNWd6DQ           2013-06-14 23:29:17, 2014-08-13 23:20:22
3  --7PUidqRWpRSpXebiyxTg  2011-02-15 17:12:00, 2011-07-28 02:46:10, 2012...
4  --7jw19RH9JKXgFohspgQw  2014-04-21 20:42:11, 2014-04-28 21:04:46, 2014...

In [19]:
# Info and null values
checkin_df.info()
checkin_df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131930 entries, 0 to 131929
Data columns (total 2 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   business_id  131930 non-null  object
 1   date         131930 non-null  object
dtypes: object(2)
memory usage: 2.0+ MB

business_id    0
date           0
dtype: int64

In [20]:
# Process check-in data
checkin_clean = checkin_df.dropna(subset=['date'])  # Remove null dates

# Split comma-separated dates and create one row per check-in
checkin_clean = (checkin_clean.assign(date=checkin_clean['date'].str.split(', '))
                 .explode('date')
                 .reset_index(drop=True))

# Convert to datetime and clean up
checkin_clean['checkin_time'] = pd.to_datetime(checkin_clean['date'])
checkin_clean = checkin_clean.drop(columns=['date'])

print("Cleaned Check-in Data:")
checkin_clean.head()

Cleaned Check-in Data:

              business_id        checkin_time
0  ---kPU91CF4Lq2-WlRu9Lw 2020-03-13 21:10:56
1  ---kPU91CF4Lq2-WlRu9Lw 2020-06-02 22:18:06
2  ---kPU91CF4Lq2-WlRu9Lw 2020-07-24 22:42:27
3  ---kPU91CF4Lq2-WlRu9Lw 2020-10-24 21:36:13
4  ---kPU91CF4Lq2-WlRu9Lw 2020-12-09 21:23:33

In [21]:
# Initialize an empty list to store the chunks
chunks = []

# Load the review dataset in chunks
for chunk in pd.read_json('/kaggle/input/yelp-dataset/yelp_academic_dataset_review.json', 
                         lines=True, 
                         chunksize=100000):
    chunks.append(chunk)

# Concatenate all chunks into a single DataFrame
review_df = pd.concat(chunks, ignore_index=True)

# Remove duplicate columns if any
review_df = review_df.loc[:, ~review_df.columns.duplicated()]

print(f"Loaded {len(review_df)} review records")
review_df.head()

Loaded 6990280 review records

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3,0,0,0,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11
1,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5,1,0,1,I've taken a lot of spin classes over the year...,2012-01-03 15:28:18
2,saUsX_uimxRlCVr67Z4Jig,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3,0,0,0,Family diner. Had the buffet. Eclectic assortm...,2014-02-05 20:30:30
3,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5,1,0,1,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03
4,Sx8TMOWLNuJBWer-0pcmoA,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4,1,0,1,Cute interior and owner (?) gave us tour of up...,2017-01-14 20:54:15

In [22]:
# Info and null values
review_df.info()
review_df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6990280 entries, 0 to 6990279
Data columns (total 9 columns):
 #   Column       Dtype
---  ------       -----
 0   review_id    object
 1   user_id      object
 2   business_id  object
 3   stars        int64
 4   useful       int64
 5   funny        int64
 6   cool         int64
 7   text         object
 8   date         datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 480.0+ MB

review_id      0
user_id        0
business_id    0
stars          0
useful         0
funny          0
cool           0
text           0
date           0
dtype: int64

In [23]:
import pandas as pd
import json

# Load tip data
def load_json_file(filepath):
    data = []
    with open(filepath, 'r') as f:
        for line in f:
            data.append(json.loads(line))
    return pd.DataFrame(data)

tip_df = load_json_file('/kaggle/input/yelp-dataset/yelp_academic_dataset_tip.json')
print(f"Loaded {len(tip_df)} review records")
tip_df.head()

Loaded 908915 review records

,user_id,business_id,text,date,compliment_count
0,AGNUgVwnZUey3gcPCJ76iw,3uLgwr0qeCNMjKenHJwPGQ,Avengers time with the ladies.,2012-05-18 02:17:21,0
1,NBN4MgHP9D3cw--SnauTkA,QoezRbYQncpRqyrLH6Iqjg,They have lots of good deserts and tasty cuban...,2013-02-05 18:35:10,0
2,-copOvldyKh1qr-vzkDEvw,MYoRNLb5chwjQe3c_k37Gg,It's open even when you think it isn't,2013-08-18 00:56:08,0
3,FjMQVZjSqY8syIO-53KFKw,hV-bABTK-glh5wj31ps_Jw,Very decent fried chicken,2017-06-27 23:05:38,0
4,ld0AperBXk1h6UbqmM80zw,_uN0OudeJ3Zl_tf6nxg5ww,Appetizers.. platter special for lunch,2012-10-06 19:43:09,0

In [24]:
# Info and null values
tip_df.info()
tip_df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 908915 entries, 0 to 908914
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   user_id           908915 non-null  object
 1   business_id       908915 non-null  object
 2   text              908915 non-null  object
 3   date              908915 non-null  object
 4   compliment_count  908915 non-null  int64
dtypes: int64(1), object(4)
memory usage: 34.7+ MB

user_id             0
business_id         0
text                0
date                0
compliment_count    0
dtype: int64

In [25]:
# Convert date to datetime
tip_df['date'] = pd.to_datetime(tip_df['date'])

# Final cleaned version
tip_clean = tip_df[['user_id', 'business_id', 'text', 'date', 'compliment_count']].copy()

# Preview
tip_clean.head()

,user_id,business_id,text,date,compliment_count
0,AGNUgVwnZUey3gcPCJ76iw,3uLgwr0qeCNMjKenHJwPGQ,Avengers time with the ladies.,2012-05-18 02:17:21,0
1,NBN4MgHP9D3cw--SnauTkA,QoezRbYQncpRqyrLH6Iqjg,They have lots of good deserts and tasty cuban...,2013-02-05 18:35:10,0
2,-copOvldyKh1qr-vzkDEvw,MYoRNLb5chwjQe3c_k37Gg,It's open even when you think it isn't,2013-08-18 00:56:08,0
3,FjMQVZjSqY8syIO-53KFKw,hV-bABTK-glh5wj31ps_Jw,Very decent fried chicken,2017-06-27 23:05:38,0
4,ld0AperBXk1h6UbqmM80zw,_uN0OudeJ3Zl_tf6nxg5ww,Appetizers.. platter special for lunch,2012-10-06 19:43:09,0

In [26]:
# User Data
import pandas as pd
import json

def load_json_file(filepath):
    data = []
    with open(filepath, 'r') as f:
        for line in f:
            data.append(json.loads(line))
    return pd.DataFrame(data)

# Load user data
user_df = load_json_file('/kaggle/input/yelp-dataset/yelp_academic_dataset_user.json')
print(f"Loaded {len(user_df)} user records")
user_df.head()

Loaded 1987897 user records

,user_id,name,review_count,yelping_since,useful,funny,cool,elite,friends,fans,...,compliment_more,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos
0,qVc8ODYU5SZjKXVBgXdI7w,Walker,585,2007-01-25 16:47:26,7217,1259,5994,2007,"NSCy54eWehBJyZdG2iE84w, pe42u7DcCH2QmI81NX-8qA...",267,...,65,55,56,18,232,844,467,467,239,180
1,j14WgRoU_-2ZE1aw1dXrJg,Daniel,4333,2009-01-25 04:35:42,43091,13066,27281,"2009,2010,2011,2012,2013,2014,2015,2016,2017,2...","ueRPE0CX75ePGMqOFVj6IQ, 52oH4DrRvzzl8wh5UXyU0A...",3138,...,264,184,157,251,1847,7054,3131,3131,1521,1946
2,2WnXYQFK0hXEoTxPtV2zvg,Steph,665,2008-07-25 10:41:00,2086,1010,1003,"2009,2010,2011,2012,2013","LuO3Bn4f3rlhyHIaNfTlnA, j9B4XdHUhDfTKVecyWQgyA...",52,...,13,10,17,3,66,96,119,119,35,18
3,SZDeASXq7o05mMNLshsdIA,Gwen,224,2005-11-29 04:38:33,512,330,299,"2009,2010,2011","enx1vVPnfdNUdPho6PH_wg, 4wOcvMLtU6a9Lslggq74Vg...",28,...,4,1,6,2,12,16,26,26,10,9
4,hA5lMy-EnncsH4JoR-hFGQ,Karen,79,2007-01-05 19:40:59,29,15,7,,"PBK4q9KEEBHhFvSXCUirIw, 3FWPpM7KU1gXeOM_ZbYMbA...",1,...,1,0,0,0,1,1,0,0,0,0

In [27]:
# Info and null values
user_df.info()
user_df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1987897 entries, 0 to 1987896
Data columns (total 22 columns):
 #   Column              Dtype
---  ------              -----
 0   user_id             object
 1   name                object
 2   review_count        int64
 3   yelping_since       object
 4   useful              int64
 5   funny               int64
 6   cool                int64
 7   elite               object
 8   friends             object
 9   fans                int64
 10  average_stars       float64
 11  compliment_hot      int64
 12  compliment_more     int64
 13  compliment_profile  int64
 14  compliment_cute     int64
 15  compliment_list     int64
 16  compliment_note     int64
 17  compliment_plain    int64
 18  compliment_cool     int64
 19  compliment_funny    int64
 20  compliment_writer   int64
 21  compliment_photos   int64
dtypes: float64(1), int64(16), object(5)
memory usage: 333.7+ MB

user_id               0
name                  0
review_count          0
yelping_since         0
useful                0
funny                 0
cool                  0
elite                 0
friends               0
fans                  0
average_stars         0
compliment_hot        0
compliment_more       0
compliment_profile    0
compliment_cute       0
compliment_list       0
compliment_note       0
compliment_plain      0
compliment_cool       0
compliment_funny      0
compliment_writer     0
compliment_photos     0
dtype: int64

In [28]:
# Convert 'yelping_since' to datetime
user_df['yelping_since'] = pd.to_datetime(user_df['yelping_since'])

In [30]:
# Install unixODBC
!apt-get update
!apt-get install -y unixodbc unixodbc-dev

# Install pyodbc
!pip install pyodbc

# Install ODBC Driver 17 for SQL Server
!curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
!curl https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list | tee /etc/apt/sources.list.d/mssql-release.list
!apt-get update
!ACCEPT_EULA=Y apt-get install -y msodbcsql17

 

import urllib
from sqlalchemy import create_engine
from sqlalchemy.sql import text

username = 'group9studentuser'  # Replace with your Azure SQL admin username
password = 'PasswordGroup9'        # Replace with your Azure SQL password
server = 'team9azureuser.database.windows.net'  # Replace with your Azure SQL server name
database = 'StudemtDB_9'  # Replace with your Azure SQL database

# Define connection parameters
driver = "ODBC Driver 17 for SQL Server"  # Ensure this driver is installed
 
# Build the ODBC connection string
odbc_str = f"DRIVER={{{driver}}};SERVER={server};PORT=1433;DATABASE={database};UID={username};PWD={password}"
 
# Encode the connection string for SQLAlchemy
connection_url = f"mssql+pyodbc:///?odbc_connect={urllib.parse.quote_plus(odbc_str)}"
 
# Create SQLAlchemy engine
engine = create_engine(connection_url)
 

with engine.connect() as connection:
    result = connection.execute(text("SELECT GETDATE();"))
    for row in result:
        print("Connected! Server date and time:", row[0])

Hit:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:3 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:4 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:6 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
W: https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
unixodbc-dev is already the newest version (2.3.9-5ubuntu0.1).
unixodbc is already the newest version (2.3.9-5ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 175 not upgraded.
Requirement already satisfied: pyodbc in /usr/local/lib/python3.10/dist-packages (5.2.0)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
100   983  100   983    0     0   5576      0 --:--:-- --:--:-- --:--:--  5585
OK
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    88  100    88    0     0    673      0 --:--:-- --:--:-- --:--:--   676
Hit:1 http://archive.ubuntu.com/ubuntu jammy InReleaset.com/ubuntu/22.04/prod jammy main
Hit:2 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:4 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:6 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease
Hit:7 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:8 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
W: https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
msodbcsql17 is already the newest version (17.10.6.1-1).
0 upgraded, 0 newly installed, 0 to remove and 175 not upgraded.
Connected! Server date and time: 2025-04-03 06:31:41.363000

In [29]:
!pip install pyodbc sqlalchemy

Collecting pyodbc
  Downloading pyodbc-5.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.7 kB)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.10/dist-packages (2.0.36)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy) (3.1.1)
Downloading pyodbc-5.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (336 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 336.0/336.0 kB 5.9 MB/s eta 0:00:00a 0:00:01
Installing collected packages: pyodbc
Successfully installed pyodbc-5.2.0

In [31]:
!curl ifconfig.me

34.75.232.187

In [32]:
def upload_dataframe_in_chunks(df, table_name, chunk_size=20000):
    total_rows = len(df)
    print(f"Uploading {total_rows} rows to '{table_name}' in chunks of {chunk_size}...")

    for start in range(0, total_rows, chunk_size):
        end = start + chunk_size
        chunk = df.iloc[start:end]

        if_exists_mode = 'replace' if start == 0 else 'append'

        try:
            chunk.to_sql(
                name=table_name,
                con=engine,
                if_exists=if_exists_mode,
                index=False
            )
            print(f"✅ Rows {start} to {end} uploaded")
        except Exception as e:
            print(f"❌ Error uploading rows {start} to {end}: {e}")
            break

In [36]:
upload_dataframe_in_chunks(business_clean, 'business_df')

Uploading 150346 rows to 'business_df' in chunks of 20000...
✅ Rows 0 to 20000 uploaded
✅ Rows 20000 to 40000 uploaded
✅ Rows 40000 to 60000 uploaded
✅ Rows 60000 to 80000 uploaded
✅ Rows 80000 to 100000 uploaded
✅ Rows 100000 to 120000 uploaded
✅ Rows 120000 to 140000 uploaded
✅ Rows 140000 to 160000 uploaded

In [33]:
upload_dataframe_in_chunks(tip_clean, 'tip_df')

Uploading 908915 rows to 'tip_df' in chunks of 20000...
✅ Rows 0 to 20000 uploaded
✅ Rows 20000 to 40000 uploaded
✅ Rows 40000 to 60000 uploaded
✅ Rows 60000 to 80000 uploaded
✅ Rows 80000 to 100000 uploaded
✅ Rows 100000 to 120000 uploaded
✅ Rows 120000 to 140000 uploaded
✅ Rows 140000 to 160000 uploaded
✅ Rows 160000 to 180000 uploaded
✅ Rows 180000 to 200000 uploaded
✅ Rows 200000 to 220000 uploaded
✅ Rows 220000 to 240000 uploaded
✅ Rows 240000 to 260000 uploaded
✅ Rows 260000 to 280000 uploaded
✅ Rows 280000 to 300000 uploaded
✅ Rows 300000 to 320000 uploaded
✅ Rows 320000 to 340000 uploaded
✅ Rows 340000 to 360000 uploaded
✅ Rows 360000 to 380000 uploaded
✅ Rows 380000 to 400000 uploaded
✅ Rows 400000 to 420000 uploaded
✅ Rows 420000 to 440000 uploaded
✅ Rows 440000 to 460000 uploaded
✅ Rows 460000 to 480000 uploaded
✅ Rows 480000 to 500000 uploaded
✅ Rows 500000 to 520000 uploaded
✅ Rows 520000 to 540000 uploaded
✅ Rows 540000 to 560000 uploaded
✅ Rows 560000 to 580000 uploaded
✅ Rows 580000 to 600000 uploaded
✅ Rows 600000 to 620000 uploaded
✅ Rows 620000 to 640000 uploaded
✅ Rows 640000 to 660000 uploaded
✅ Rows 660000 to 680000 uploaded
✅ Rows 680000 to 700000 uploaded
✅ Rows 700000 to 720000 uploaded
✅ Rows 720000 to 740000 uploaded
✅ Rows 740000 to 760000 uploaded
✅ Rows 760000 to 780000 uploaded
✅ Rows 780000 to 800000 uploaded
✅ Rows 800000 to 820000 uploaded
✅ Rows 820000 to 840000 uploaded
✅ Rows 840000 to 860000 uploaded
✅ Rows 860000 to 880000 uploaded
✅ Rows 880000 to 900000 uploaded
✅ Rows 900000 to 920000 uploaded

In [34]:
upload_dataframe_in_chunks(checkin_clean, 'checkin_df')

Uploading 13356875 rows to 'checkin_df' in chunks of 20000...
✅ Rows 0 to 20000 uploaded
✅ Rows 20000 to 40000 uploaded
✅ Rows 40000 to 60000 uploaded
✅ Rows 60000 to 80000 uploaded
✅ Rows 80000 to 100000 uploaded
✅ Rows 100000 to 120000 uploaded
✅ Rows 120000 to 140000 uploaded
✅ Rows 140000 to 160000 uploaded
✅ Rows 160000 to 180000 uploaded
✅ Rows 180000 to 200000 uploaded
✅ Rows 200000 to 220000 uploaded
✅ Rows 220000 to 240000 uploaded
✅ Rows 240000 to 260000 uploaded
✅ Rows 260000 to 280000 uploaded
✅ Rows 280000 to 300000 uploaded
✅ Rows 300000 to 320000 uploaded
✅ Rows 320000 to 340000 uploaded
✅ Rows 340000 to 360000 uploaded
✅ Rows 360000 to 380000 uploaded
✅ Rows 380000 to 400000 uploaded
✅ Rows 400000 to 420000 uploaded
✅ Rows 420000 to 440000 uploaded
✅ Rows 440000 to 460000 uploaded
✅ Rows 460000 to 480000 uploaded
✅ Rows 480000 to 500000 uploaded
✅ Rows 500000 to 520000 uploaded
✅ Rows 520000 to 540000 uploaded
✅ Rows 540000 to 560000 uploaded
✅ Rows 560000 to 580000 uploaded
✅ Rows 580000 to 600000 uploaded
✅ Rows 600000 to 620000 uploaded
✅ Rows 620000 to 640000 uploaded
✅ Rows 640000 to 660000 uploaded
✅ Rows 660000 to 680000 uploaded
✅ Rows 680000 to 700000 uploaded
✅ Rows 700000 to 720000 uploaded
✅ Rows 720000 to 740000 uploaded
✅ Rows 740000 to 760000 uploaded
✅ Rows 760000 to 780000 uploaded
✅ Rows 780000 to 800000 uploaded
✅ Rows 800000 to 820000 uploaded
✅ Rows 820000 to 840000 uploaded
✅ Rows 840000 to 860000 uploaded
✅ Rows 860000 to 880000 uploaded
✅ Rows 880000 to 900000 uploaded
✅ Rows 900000 to 920000 uploaded
✅ Rows 920000 to 940000 uploaded
✅ Rows 940000 to 960000 uploaded
✅ Rows 960000 to 980000 uploaded
✅ Rows 980000 to 1000000 uploaded
✅ Rows 1000000 to 1020000 uploaded
✅ Rows 1020000 to 1040000 uploaded
✅ Rows 1040000 to 1060000 uploaded
✅ Rows 1060000 to 1080000 uploaded
✅ Rows 1080000 to 1100000 uploaded
✅ Rows 1100000 to 1120000 uploaded
✅ Rows 1120000 to 1140000 uploaded
✅ Rows 1140000 to 1160000 uploaded
✅ Rows 1160000 to 1180000 uploaded
✅ Rows 1180000 to 1200000 uploaded
✅ Rows 1200000 to 1220000 uploaded
✅ Rows 1220000 to 1240000 uploaded
✅ Rows 1240000 to 1260000 uploaded
✅ Rows 1260000 to 1280000 uploaded
✅ Rows 1280000 to 1300000 uploaded
✅ Rows 1300000 to 1320000 uploaded
✅ Rows 1320000 to 1340000 uploaded
✅ Rows 1340000 to 1360000 uploaded
✅ Rows 1360000 to 1380000 uploaded
✅ Rows 1380000 to 1400000 uploaded
✅ Rows 1400000 to 1420000 uploaded
✅ Rows 1420000 to 1440000 uploaded
✅ Rows 1440000 to 1460000 uploaded
✅ Rows 1460000 to 1480000 uploaded
✅ Rows 1480000 to 1500000 uploaded
✅ Rows 1500000 to 1520000 uploaded
✅ Rows 1520000 to 1540000 uploaded
✅ Rows 1540000 to 1560000 uploaded
✅ Rows 1560000 to 1580000 uploaded
✅ Rows 1580000 to 1600000 uploaded
✅ Rows 1600000 to 1620000 uploaded
✅ Rows 1620000 to 1640000 uploaded
✅ Rows 1640000 to 1660000 uploaded
✅ Rows 1660000 to 1680000 uploaded
✅ Rows 1680000 to 1700000 uploaded
✅ Rows 1700000 to 1720000 uploaded
✅ Rows 1720000 to 1740000 uploaded
✅ Rows 1740000 to 1760000 uploaded
✅ Rows 1760000 to 1780000 uploaded
✅ Rows 1780000 to 1800000 uploaded
✅ Rows 1800000 to 1820000 uploaded
✅ Rows 1820000 to 1840000 uploaded
✅ Rows 1840000 to 1860000 uploaded
✅ Rows 1860000 to 1880000 uploaded
✅ Rows 1880000 to 1900000 uploaded
✅ Rows 1900000 to 1920000 uploaded
✅ Rows 1920000 to 1940000 uploaded
✅ Rows 1940000 to 1960000 uploaded
✅ Rows 1960000 to 1980000 uploaded
✅ Rows 1980000 to 2000000 uploaded
✅ Rows 2000000 to 2020000 uploaded
✅ Rows 2020000 to 2040000 uploaded
✅ Rows 2040000 to 2060000 uploaded
✅ Rows 2060000 to 2080000 uploaded
✅ Rows 2080000 to 2100000 uploaded
✅ Rows 2100000 to 2120000 uploaded
✅ Rows 2120000 to 2140000 uploaded
✅ Rows 2140000 to 2160000 uploaded
✅ Rows 2160000 to 2180000 uploaded
✅ Rows 2180000 to 2200000 uploaded
✅ Rows 2200000 to 2220000 uploaded
✅ Rows 2220000 to 2240000 uploaded
✅ Rows 2240000 to 2260000 uploaded
✅ Rows 2260000 to 2280000 uploaded
✅ Rows 2280000 to 2300000 uploaded
✅ Rows 2300000 to 2320000 uploaded
✅ Rows 2320000 to 2340000 uploaded
✅ Rows 2340000 to 2360000 uploaded
✅ Rows 2360000 to 2380000 uploaded
✅ Rows 2380000 to 2400000 uploaded
✅ Rows 2400000 to 2420000 uploaded
✅ Rows 2420000 to 2440000 uploaded
✅ Rows 2440000 to 2460000 uploaded
✅ Rows 2460000 to 2480000 uploaded
✅ Rows 2480000 to 2500000 uploaded
✅ Rows 2500000 to 2520000 uploaded
✅ Rows 2520000 to 2540000 uploaded
✅ Rows 2540000 to 2560000 uploaded
✅ Rows 2560000 to 2580000 uploaded
✅ Rows 2580000 to 2600000 uploaded
✅ Rows 2600000 to 2620000 uploaded
✅ Rows 2620000 to 2640000 uploaded
✅ Rows 2640000 to 2660000 uploaded
✅ Rows 2660000 to 2680000 uploaded
✅ Rows 2680000 to 2700000 uploaded
✅ Rows 2700000 to 2720000 uploaded
✅ Rows 2720000 to 2740000 uploaded
✅ Rows 2740000 to 2760000 uploaded
✅ Rows 2760000 to 2780000 uploaded
✅ Rows 2780000 to 2800000 uploaded
✅ Rows 2800000 to 2820000 uploaded
✅ Rows 2820000 to 2840000 uploaded
✅ Rows 2840000 to 2860000 uploaded
✅ Rows 2860000 to 2880000 uploaded
✅ Rows 2880000 to 2900000 uploaded
✅ Rows 2900000 to 2920000 uploaded
✅ Rows 2920000 to 2940000 uploaded
✅ Rows 2940000 to 2960000 uploaded
✅ Rows 2960000 to 2980000 uploaded
✅ Rows 2980000 to 3000000 uploaded
✅ Rows 3000000 to 3020000 uploaded
✅ Rows 3020000 to 3040000 uploaded
✅ Rows 3040000 to 3060000 uploaded
✅ Rows 3060000 to 3080000 uploaded
✅ Rows 3080000 to 3100000 uploaded
✅ Rows 3100000 to 3120000 uploaded
✅ Rows 3120000 to 3140000 uploaded
✅ Rows 3140000 to 3160000 uploaded
✅ Rows 3160000 to 3180000 uploaded
✅ Rows 3180000 to 3200000 uploaded
✅ Rows 3200000 to 3220000 uploaded
✅ Rows 3220000 to 3240000 uploaded
✅ Rows 3240000 to 3260000 uploaded
✅ Rows 3260000 to 3280000 uploaded
✅ Rows 3280000 to 3300000 uploaded
✅ Rows 3300000 to 3320000 uploaded
✅ Rows 4860000 to 4880000 uploaded
✅ Rows 4880000 to 4900000 uploaded
✅ Rows 4900000 to 4920000 uploaded
✅ Rows 4920000 to 4940000 uploaded
✅ Rows 4940000 to 4960000 uploaded
✅ Rows 4960000 to 4980000 uploaded
✅ Rows 4980000 to 5000000 uploaded
✅ Rows 5000000 to 5020000 uploaded
✅ Rows 5020000 to 5040000 uploaded
✅ Rows 5040000 to 5060000 uploaded
✅ Rows 5060000 to 5080000 uploaded
✅ Rows 5080000 to 5100000 uploaded
✅ Rows 5100000 to 5120000 uploaded
✅ Rows 5120000 to 5140000 uploaded
✅ Rows 5140000 to 5160000 uploaded
✅ Rows 5160000 to 5180000 uploaded
✅ Rows 5180000 to 5200000 uploaded
✅ Rows 5200000 to 5220000 uploaded
✅ Rows 5220000 to 5240000 uploaded
✅ Rows 5240000 to 5260000 uploaded
✅ Rows 5260000 to 5280000 uploaded
✅ Rows 5280000 to 5300000 uploaded
✅ Rows 5300000 to 5320000 uploaded
✅ Rows 5320000 to 5340000 uploaded
✅ Rows 5340000 to 5360000 uploaded
✅ Rows 5360000 to 5380000 uploaded
✅ Rows 5380000 to 5400000 uploaded
✅ Rows 5400000 to 5420000 uploaded
✅ Rows 5420000 to 5440000 uploaded
✅ Rows 5440000 to 5460000 uploaded
✅ Rows 5460000 to 5480000 uploaded
✅ Rows 5480000 to 5500000 uploaded
✅ Rows 5500000 to 5520000 uploaded
✅ Rows 5520000 to 5540000 uploaded
✅ Rows 5540000 to 5560000 uploaded
✅ Rows 5560000 to 5580000 uploaded
✅ Rows 5580000 to 5600000 uploaded
✅ Rows 5600000 to 5620000 uploaded
✅ Rows 5620000 to 5640000 uploaded
✅ Rows 5640000 to 5660000 uploaded
✅ Rows 5660000 to 5680000 uploaded
✅ Rows 5680000 to 5700000 uploaded
✅ Rows 5700000 to 5720000 uploaded
✅ Rows 5720000 to 5740000 uploaded
✅ Rows 5740000 to 5760000 uploaded
✅ Rows 5760000 to 5780000 uploaded
✅ Rows 5780000 to 5800000 uploaded
✅ Rows 5800000 to 5820000 uploaded
✅ Rows 5820000 to 5840000 uploaded
✅ Rows 5840000 to 5860000 uploaded
✅ Rows 5860000 to 5880000 uploaded
✅ Rows 5880000 to 5900000 uploaded
✅ Rows 5900000 to 5920000 uploaded
✅ Rows 5920000 to 5940000 uploaded
✅ Rows 5940000 to 5960000 uploaded
✅ Rows 5960000 to 5980000 uploaded
✅ Rows 5980000 to 6000000 uploaded
✅ Rows 6000000 to 6020000 uploaded
✅ Rows 6020000 to 6040000 uploaded
✅ Rows 6040000 to 6060000 uploaded
✅ Rows 6060000 to 6080000 uploaded
✅ Rows 6080000 to 6100000 uploaded
✅ Rows 6100000 to 6120000 uploaded
✅ Rows 6120000 to 6140000 uploaded
✅ Rows 6140000 to 6160000 uploaded
✅ Rows 6160000 to 6180000 uploaded
✅ Rows 6180000 to 6200000 uploaded
✅ Rows 6200000 to 6220000 uploaded
✅ Rows 6220000 to 6240000 uploaded
✅ Rows 6240000 to 6260000 uploaded
✅ Rows 6260000 to 6280000 uploaded
✅ Rows 6280000 to 6300000 uploaded
✅ Rows 6300000 to 6320000 uploaded
✅ Rows 6320000 to 6340000 uploaded
✅ Rows 6340000 to 6360000 uploaded
✅ Rows 6360000 to 6380000 uploaded
✅ Rows 6380000 to 6400000 uploaded
✅ Rows 6400000 to 6420000 uploaded
✅ Rows 6420000 to 6440000 uploaded
✅ Rows 6440000 to 6460000 uploaded
✅ Rows 6460000 to 6480000 uploaded
✅ Rows 6480000 to 6500000 uploaded
✅ Rows 6500000 to 6520000 uploaded
✅ Rows 6520000 to 6540000 uploaded
✅ Rows 6540000 to 6560000 uploaded
✅ Rows 6560000 to 6580000 uploaded
✅ Rows 6580000 to 6600000 uploaded
✅ Rows 6600000 to 6620000 uploaded
✅ Rows 6620000 to 6640000 uploaded
✅ Rows 6640000 to 6660000 uploaded
✅ Rows 6660000 to 6680000 uploaded
✅ Rows 6680000 to 6700000 uploaded
✅ Rows 6700000 to 6720000 uploaded
✅ Rows 6720000 to 6740000 uploaded
✅ Rows 6740000 to 6760000 uploaded
✅ Rows 6760000 to 6780000 uploaded
✅ Rows 6780000 to 6800000 uploaded
✅ Rows 6800000 to 6820000 uploaded
✅ Rows 6820000 to 6840000 uploaded
✅ Rows 6840000 to 6860000 uploaded
✅ Rows 6860000 to 6880000 uploaded
✅ Rows 6880000 to 6900000 uploaded
✅ Rows 6900000 to 6920000 uploaded
✅ Rows 6920000 to 6940000 uploaded
✅ Rows 6940000 to 6960000 uploaded
✅ Rows 6960000 to 6980000 uploaded
✅ Rows 6980000 to 7000000 uploaded
✅ Rows 7000000 to 7020000 uploaded
✅ Rows 7020000 to 7040000 uploaded
✅ Rows 7040000 to 7060000 uploaded
✅ Rows 7060000 to 7080000 uploaded
✅ Rows 7080000 to 7100000 uploaded
✅ Rows 7100000 to 7120000 uploaded
✅ Rows 7120000 to 7140000 uploaded
✅ Rows 7140000 to 7160000 uploaded
✅ Rows 7160000 to 7180000 uploaded
✅ Rows 7180000 to 7200000 uploaded
✅ Rows 7200000 to 7220000 uploaded
✅ Rows 7220000 to 7240000 uploaded
✅ Rows 7240000 to 7260000 uploaded
✅ Rows 7260000 to 7280000 uploaded
✅ Rows 7280000 to 7300000 uploaded
✅ Rows 7300000 to 7320000 uploaded
✅ Rows 7320000 to 7340000 uploaded
✅ Rows 7340000 to 7360000 uploaded
✅ Rows 7360000 to 7380000 uploaded
✅ Rows 7380000 to 7400000 uploaded
✅ Rows 7400000 to 7420000 uploaded
✅ Rows 7420000 to 7440000 uploaded
✅ Rows 7440000 to 7460000 uploaded
✅ Rows 7460000 to 7480000 uploaded
✅ Rows 7480000 to 7500000 uploaded
✅ Rows 7500000 to 7520000 uploaded
✅ Rows 7520000 to 7540000 uploaded
✅ Rows 7540000 to 7560000 uploaded
✅ Rows 7560000 to 7580000 uploaded
✅ Rows 7580000 to 7600000 uploaded
✅ Rows 7600000 to 7620000 uploaded
✅ Rows 7620000 to 7640000 uploaded
✅ Rows 7640000 to 7660000 uploaded
✅ Rows 7660000 to 7680000 uploaded
✅ Rows 7680000 to 7700000 uploaded
✅ Rows 7700000 to 7720000 uploaded
✅ Rows 7720000 to 7740000 uploaded
✅ Rows 7740000 to 7760000 uploaded
✅ Rows 7760000 to 7780000 uploaded
✅ Rows 7780000 to 7800000 uploaded
✅ Rows 7800000 to 7820000 uploaded
✅ Rows 7820000 to 7840000 uploaded
✅ Rows 7840000 to 7860000 uploaded
✅ Rows 7860000 to 7880000 uploaded
✅ Rows 7880000 to 7900000 uploaded
✅ Rows 7900000 to 7920000 uploaded
✅ Rows 7920000 to 7940000 uploaded
✅ Rows 7940000 to 7960000 uploaded
✅ Rows 7960000 to 7980000 uploaded
✅ Rows 7980000 to 8000000 uploaded
✅ Rows 8000000 to 8020000 uploaded
✅ Rows 8020000 to 8040000 uploaded
✅ Rows 8040000 to 8060000 uploaded
✅ Rows 8060000 to 8080000 uploaded
✅ Rows 8080000 to 8100000 uploaded
✅ Rows 8100000 to 8120000 uploaded
✅ Rows 8120000 to 8140000 uploaded
✅ Rows 8140000 to 8160000 uploaded
✅ Rows 8160000 to 8180000 uploaded
✅ Rows 8180000 to 8200000 uploaded
✅ Rows 8200000 to 8220000 uploaded
✅ Rows 8220000 to 8240000 uploaded
✅ Rows 8240000 to 8260000 uploaded
✅ Rows 8260000 to 8280000 uploaded
✅ Rows 8280000 to 8300000 uploaded
✅ Rows 8300000 to 8320000 uploaded
✅ Rows 8320000 to 8340000 uploaded
✅ Rows 8340000 to 8360000 uploaded
✅ Rows 8360000 to 8380000 uploaded
✅ Rows 8380000 to 8400000 uploaded
✅ Rows 8400000 to 8420000 uploaded
✅ Rows 8420000 to 8440000 uploaded
✅ Rows 8440000 to 8460000 uploaded
✅ Rows 8460000 to 8480000 uploaded
✅ Rows 8480000 to 8500000 uploaded
✅ Rows 8500000 to 8520000 uploaded
✅ Rows 8520000 to 8540000 uploaded
✅ Rows 8540000 to 8560000 uploaded
✅ Rows 8560000 to 8580000 uploaded
✅ Rows 8580000 to 8600000 uploaded
✅ Rows 8600000 to 8620000 uploaded
✅ Rows 8620000 to 8640000 uploaded
✅ Rows 8640000 to 8660000 uploaded
✅ Rows 8660000 to 8680000 uploaded
✅ Rows 8680000 to 8700000 uploaded
✅ Rows 8700000 to 8720000 uploaded
✅ Rows 8720000 to 8740000 uploaded
✅ Rows 8740000 to 8760000 uploaded
✅ Rows 8760000 to 8780000 uploaded
✅ Rows 8780000 to 8800000 uploaded
✅ Rows 8800000 to 8820000 uploaded
✅ Rows 8820000 to 8840000 uploaded
✅ Rows 8840000 to 8860000 uploaded
✅ Rows 8860000 to 8880000 uploaded
✅ Rows 8880000 to 8900000 uploaded
✅ Rows 8900000 to 8920000 uploaded
✅ Rows 8920000 to 8940000 uploaded
✅ Rows 8940000 to 8960000 uploaded
✅ Rows 8960000 to 8980000 uploaded
✅ Rows 8980000 to 9000000 uploaded
✅ Rows 9000000 to 9020000 uploaded
✅ Rows 9020000 to 9040000 uploaded
✅ Rows 9040000 to 9060000 uploaded
✅ Rows 9060000 to 9080000 uploaded
✅ Rows 9080000 to 9100000 uploaded
✅ Rows 9100000 to 9120000 uploaded
✅ Rows 9120000 to 9140000 uploaded
✅ Rows 9140000 to 9160000 uploaded
✅ Rows 9160000 to 9180000 uploaded
✅ Rows 9180000 to 9200000 uploaded
✅ Rows 9200000 to 9220000 uploaded
✅ Rows 9220000 to 9240000 uploaded
✅ Rows 9240000 to 9260000 uploaded
✅ Rows 9260000 to 9280000 uploaded
✅ Rows 9280000 to 9300000 uploaded
✅ Rows 9300000 to 9320000 uploaded
✅ Rows 9320000 to 9340000 uploaded
✅ Rows 9340000 to 9360000 uploaded
✅ Rows 9360000 to 9380000 uploaded
✅ Rows 9380000 to 9400000 uploaded
✅ Rows 9400000 to 9420000 uploaded
✅ Rows 9420000 to 9440000 uploaded
✅ Rows 9440000 to 9460000 uploaded
✅ Rows 9460000 to 9480000 uploaded
✅ Rows 9480000 to 9500000 uploaded
✅ Rows 9500000 to 9520000 uploaded
✅ Rows 9520000 to 9540000 uploaded
✅ Rows 9540000 to 9560000 uploaded
✅ Rows 9560000 to 9580000 uploaded
✅ Rows 9580000 to 9600000 uploaded
✅ Rows 9600000 to 9620000 uploaded
✅ Rows 9620000 to 9640000 uploaded
✅ Rows 9640000 to 9660000 uploaded
✅ Rows 9660000 to 9680000 uploaded
✅ Rows 9680000 to 9700000 uploaded
✅ Rows 9700000 to 9720000 uploaded
✅ Rows 9720000 to 9740000 uploaded
✅ Rows 9740000 to 9760000 uploaded
✅ Rows 9760000 to 9780000 uploaded
✅ Rows 9780000 to 9800000 uploaded
✅ Rows 9800000 to 9820000 uploaded
✅ Rows 9820000 to 9840000 uploaded
✅ Rows 9840000 to 9860000 uploaded
✅ Rows 9860000 to 9880000 uploaded
✅ Rows 9880000 to 9900000 uploaded
✅ Rows 9900000 to 9920000 uploaded
✅ Rows 9920000 to 9940000 uploaded
✅ Rows 9940000 to 9960000 uploaded
✅ Rows 9960000 to 9980000 uploaded
✅ Rows 9980000 to 10000000 uploaded
✅ Rows 10000000 to 10020000 uploaded
✅ Rows 10020000 to 10040000 uploaded
✅ Rows 10040000 to 10060000 uploaded
✅ Rows 10060000 to 10080000 uploaded
✅ Rows 10080000 to 10100000 uploaded
✅ Rows 10100000 to 10120000 uploaded
✅ Rows 10120000 to 10140000 uploaded
✅ Rows 10140000 to 10160000 uploaded
✅ Rows 10160000 to 10180000 uploaded
✅ Rows 10180000 to 10200000 uploaded
✅ Rows 10200000 to 10220000 uploaded
✅ Rows 10220000 to 10240000 uploaded
✅ Rows 10240000 to 10260000 uploaded
✅ Rows 10260000 to 10280000 uploaded
✅ Rows 10280000 to 10300000 uploaded
✅ Rows 10300000 to 10320000 uploaded
✅ Rows 10320000 to 10340000 uploaded
✅ Rows 10340000 to 10360000 uploaded
✅ Rows 10360000 to 10380000 uploaded
✅ Rows 10380000 to 10400000 uploaded
✅ Rows 10400000 to 10420000 uploaded
✅ Rows 10420000 to 10440000 uploaded
✅ Rows 10440000 to 10460000 uploaded
✅ Rows 10460000 to 10480000 uploaded
✅ Rows 10480000 to 10500000 uploaded
✅ Rows 10500000 to 10520000 uploaded
✅ Rows 10520000 to 10540000 uploaded
✅ Rows 10540000 to 10560000 uploaded
✅ Rows 10560000 to 10580000 uploaded
✅ Rows 10580000 to 10600000 uploaded
✅ Rows 10600000 to 10620000 uploaded
✅ Rows 10620000 to 10640000 uploaded
✅ Rows 10640000 to 10660000 uploaded
✅ Rows 10660000 to 10680000 uploaded
✅ Rows 10680000 to 10700000 uploaded
✅ Rows 10700000 to 10720000 uploaded
✅ Rows 10720000 to 10740000 uploaded
✅ Rows 10740000 to 10760000 uploaded
✅ Rows 10760000 to 10780000 uploaded
✅ Rows 10780000 to 10800000 uploaded
✅ Rows 10800000 to 10820000 uploaded
✅ Rows 10820000 to 10840000 uploaded
✅ Rows 10840000 to 10860000 uploaded
✅ Rows 10860000 to 10880000 uploaded
✅ Rows 10880000 to 10900000 uploaded
✅ Rows 10900000 to 10920000 uploaded
✅ Rows 10920000 to 10940000 uploaded
✅ Rows 10940000 to 10960000 uploaded
✅ Rows 10960000 to 10980000 uploaded
✅ Rows 10980000 to 11000000 uploaded
✅ Rows 11000000 to 11020000 uploaded
✅ Rows 11020000 to 11040000 uploaded
✅ Rows 11040000 to 11060000 uploaded
✅ Rows 11060000 to 11080000 uploaded
✅ Rows 11080000 to 11100000 uploaded
✅ Rows 11100000 to 11120000 uploaded
✅ Rows 11120000 to 11140000 uploaded
✅ Rows 11140000 to 11160000 uploaded
✅ Rows 11160000 to 11180000 uploaded
✅ Rows 11180000 to 11200000 uploaded
✅ Rows 11200000 to 11220000 uploaded
✅ Rows 11220000 to 11240000 uploaded
✅ Rows 11240000 to 11260000 uploaded
✅ Rows 11260000 to 11280000 uploaded
✅ Rows 11280000 to 11300000 uploaded
✅ Rows 11300000 to 11320000 uploaded
✅ Rows 11320000 to 11340000 uploaded
✅ Rows 11340000 to 11360000 uploaded
✅ Rows 11360000 to 11380000 uploaded
✅ Rows 11380000 to 11400000 uploaded
✅ Rows 11400000 to 11420000 uploaded
✅ Rows 11420000 to 11440000 uploaded
✅ Rows 11440000 to 11460000 uploaded
✅ Rows 11460000 to 11480000 uploaded
✅ Rows 11480000 to 11500000 uploaded
✅ Rows 11500000 to 11520000 uploaded
✅ Rows 11520000 to 11540000 uploaded
✅ Rows 11540000 to 11560000 uploaded
✅ Rows 11560000 to 11580000 uploaded
✅ Rows 11580000 to 11600000 uploaded
✅ Rows 11600000 to 11620000 uploaded
✅ Rows 11620000 to 11640000 uploaded
✅ Rows 11640000 to 11660000 uploaded
✅ Rows 11660000 to 11680000 uploaded
✅ Rows 11680000 to 11700000 uploaded
✅ Rows 11700000 to 11720000 uploaded
✅ Rows 11720000 to 11740000 uploaded
✅ Rows 11740000 to 11760000 uploaded
✅ Rows 11760000 to 11780000 uploaded
✅ Rows 11780000 to 11800000 uploaded
✅ Rows 11800000 to 11820000 uploaded
✅ Rows 11820000 to 11840000 uploaded
✅ Rows 11840000 to 11860000 uploaded
✅ Rows 11860000 to 11880000 uploaded
✅ Rows 11880000 to 11900000 uploaded
✅ Rows 11900000 to 11920000 uploaded
✅ Rows 11920000 to 11940000 uploaded
✅ Rows 11940000 to 11960000 uploaded
✅ Rows 11960000 to 11980000 uploaded
✅ Rows 11980000 to 12000000 uploaded
✅ Rows 12000000 to 12020000 uploaded
✅ Rows 12020000 to 12040000 uploaded
✅ Rows 12040000 to 12060000 uploaded
✅ Rows 12060000 to 12080000 uploaded
✅ Rows 12080000 to 12100000 uploaded
✅ Rows 12100000 to 12120000 uploaded
✅ Rows 12120000 to 12140000 uploaded
✅ Rows 12140000 to 12160000 uploaded
✅ Rows 12160000 to 12180000 uploaded
✅ Rows 12180000 to 12200000 uploaded
✅ Rows 12200000 to 12220000 uploaded
✅ Rows 12220000 to 12240000 uploaded
✅ Rows 12240000 to 12260000 uploaded
✅ Rows 12260000 to 12280000 uploaded
✅ Rows 12280000 to 12300000 uploaded
✅ Rows 12300000 to 12320000 uploaded
✅ Rows 12320000 to 12340000 uploaded
✅ Rows 12340000 to 12360000 uploaded
✅ Rows 12360000 to 12380000 uploaded
✅ Rows 12380000 to 12400000 uploaded
✅ Rows 12400000 to 12420000 uploaded
✅ Rows 12420000 to 12440000 uploaded
✅ Rows 12440000 to 12460000 uploaded
✅ Rows 12460000 to 12480000 uploaded
✅ Rows 12480000 to 12500000 uploaded
✅ Rows 12500000 to 12520000 uploaded
✅ Rows 12520000 to 12540000 uploaded
✅ Rows 12540000 to 12560000 uploaded
✅ Rows 12560000 to 12580000 uploaded
✅ Rows 12580000 to 12600000 uploaded
✅ Rows 12600000 to 12620000 uploaded
✅ Rows 12620000 to 12640000 uploaded
✅ Rows 12640000 to 12660000 uploaded
✅ Rows 12660000 to 12680000 uploaded
✅ Rows 12680000 to 12700000 uploaded
✅ Rows 12700000 to 12720000 uploaded
✅ Rows 12720000 to 12740000 uploaded
✅ Rows 12740000 to 12760000 uploaded
✅ Rows 12760000 to 12780000 uploaded
✅ Rows 12780000 to 12800000 uploaded
✅ Rows 12800000 to 12820000 uploaded

In [35]:
upload_dataframe_in_chunks(user_df, 'user_df')

Uploading 1987897 rows to 'user_df' in chunks of 20000...
✅ Rows 0 to 20000 uploaded
✅ Rows 20000 to 40000 uploaded
✅ Rows 40000 to 60000 uploaded
✅ Rows 60000 to 80000 uploaded
✅ Rows 80000 to 100000 uploaded
✅ Rows 100000 to 120000 uploaded
✅ Rows 120000 to 140000 uploaded
✅ Rows 140000 to 160000 uploaded
✅ Rows 160000 to 180000 uploaded
✅ Rows 180000 to 200000 uploaded
✅ Rows 200000 to 220000 uploaded
✅ Rows 220000 to 240000 uploaded
✅ Rows 240000 to 260000 uploaded
✅ Rows 260000 to 280000 uploaded
✅ Rows 280000 to 300000 uploaded
✅ Rows 300000 to 320000 uploaded
✅ Rows 320000 to 340000 uploaded
✅ Rows 340000 to 360000 uploaded
✅ Rows 360000 to 380000 uploaded
✅ Rows 380000 to 400000 uploaded
✅ Rows 400000 to 420000 uploaded
✅ Rows 420000 to 440000 uploaded
✅ Rows 440000 to 460000 uploaded
✅ Rows 460000 to 480000 uploaded
✅ Rows 480000 to 500000 uploaded
✅ Rows 500000 to 520000 uploaded
✅ Rows 520000 to 540000 uploaded
✅ Rows 540000 to 560000 uploaded
✅ Rows 560000 to 580000 uploaded
✅ Rows 580000 to 600000 uploaded
✅ Rows 600000 to 620000 uploaded
✅ Rows 620000 to 640000 uploaded
✅ Rows 640000 to 660000 uploaded
✅ Rows 660000 to 680000 uploaded
✅ Rows 680000 to 700000 uploaded
✅ Rows 700000 to 720000 uploaded
✅ Rows 720000 to 740000 uploaded
✅ Rows 740000 to 760000 uploaded
✅ Rows 760000 to 780000 uploaded
✅ Rows 780000 to 800000 uploaded
✅ Rows 800000 to 820000 uploaded
✅ Rows 820000 to 840000 uploaded
✅ Rows 840000 to 860000 uploaded
✅ Rows 860000 to 880000 uploaded
✅ Rows 880000 to 900000 uploaded
✅ Rows 900000 to 920000 uploaded
✅ Rows 920000 to 940000 uploaded
✅ Rows 940000 to 960000 uploaded
✅ Rows 960000 to 980000 uploaded
✅ Rows 980000 to 1000000 uploaded
✅ Rows 1000000 to 1020000 uploaded
✅ Rows 1020000 to 1040000 uploaded
✅ Rows 1040000 to 1060000 uploaded
✅ Rows 1060000 to 1080000 uploaded
✅ Rows 1080000 to 1100000 uploaded
✅ Rows 1100000 to 1120000 uploaded
✅ Rows 1120000 to 1140000 uploaded
✅ Rows 1140000 to 1160000 uploaded
✅ Rows 1160000 to 1180000 uploaded
✅ Rows 1180000 to 1200000 uploaded
✅ Rows 1200000 to 1220000 uploaded
✅ Rows 1220000 to 1240000 uploaded
✅ Rows 1240000 to 1260000 uploaded
✅ Rows 1260000 to 1280000 uploaded
✅ Rows 1280000 to 1300000 uploaded
✅ Rows 1300000 to 1320000 uploaded
✅ Rows 1320000 to 1340000 uploaded
✅ Rows 1340000 to 1360000 uploaded
✅ Rows 1360000 to 1380000 uploaded
✅ Rows 1380000 to 1400000 uploaded
✅ Rows 1400000 to 1420000 uploaded
✅ Rows 1420000 to 1440000 uploaded
✅ Rows 1440000 to 1460000 uploaded
✅ Rows 1460000 to 1480000 uploaded
✅ Rows 1640000 to 1660000 uploaded
✅ Rows 1660000 to 1680000 uploaded
✅ Rows 1680000 to 1700000 uploaded
✅ Rows 1700000 to 1720000 uploaded
✅ Rows 1720000 to 1740000 uploaded
✅ Rows 1740000 to 1760000 uploaded
✅ Rows 1760000 to 1780000 uploaded
✅ Rows 1780000 to 1800000 uploaded
✅ Rows 1800000 to 1820000 uploaded
✅ Rows 1820000 to 1840000 uploaded
✅ Rows 1840000 to 1860000 uploaded
✅ Rows 1860000 to 1880000 uploaded
✅ Rows 1880000 to 1900000 uploaded
✅ Rows 1900000 to 1920000 uploaded
✅ Rows 1920000 to 1940000 uploaded
✅ Rows 1940000 to 1960000 uploaded
✅ Rows 1960000 to 1980000 uploaded
✅ Rows 1980000 to 2000000 uploaded

In [36]:
upload_dataframe_in_chunks(review_df, 'review_df')

Uploading 6990280 rows to 'review_df' in chunks of 20000...
✅ Rows 0 to 20000 uploaded
✅ Rows 20000 to 40000 uploaded
✅ Rows 40000 to 60000 uploaded
✅ Rows 60000 to 80000 uploaded
✅ Rows 80000 to 100000 uploaded
✅ Rows 100000 to 120000 uploaded
✅ Rows 120000 to 140000 uploaded
✅ Rows 140000 to 160000 uploaded
✅ Rows 160000 to 180000 uploaded
✅ Rows 180000 to 200000 uploaded
✅ Rows 200000 to 220000 uploaded
✅ Rows 220000 to 240000 uploaded
✅ Rows 240000 to 260000 uploaded
✅ Rows 260000 to 280000 uploaded
✅ Rows 280000 to 300000 uploaded
✅ Rows 300000 to 320000 uploaded
✅ Rows 320000 to 340000 uploaded
✅ Rows 340000 to 360000 uploaded
✅ Rows 360000 to 380000 uploaded
✅ Rows 380000 to 400000 uploaded
✅ Rows 400000 to 420000 uploaded
✅ Rows 420000 to 440000 uploaded
✅ Rows 440000 to 460000 uploaded
✅ Rows 460000 to 480000 uploaded
✅ Rows 480000 to 500000 uploaded
✅ Rows 500000 to 520000 uploaded
✅ Rows 520000 to 540000 uploaded
✅ Rows 540000 to 560000 uploaded
✅ Rows 560000 to 580000 uploaded
✅ Rows 580000 to 600000 uploaded
✅ Rows 600000 to 620000 uploaded
✅ Rows 620000 to 640000 uploaded
✅ Rows 640000 to 660000 uploaded
✅ Rows 660000 to 680000 uploaded
✅ Rows 680000 to 700000 uploaded
✅ Rows 700000 to 720000 uploaded
✅ Rows 720000 to 740000 uploaded
✅ Rows 740000 to 760000 uploaded
✅ Rows 760000 to 780000 uploaded
✅ Rows 780000 to 800000 uploaded
✅ Rows 800000 to 820000 uploaded
✅ Rows 820000 to 840000 uploaded
✅ Rows 840000 to 860000 uploaded
✅ Rows 860000 to 880000 uploaded
✅ Rows 880000 to 900000 uploaded
✅ Rows 900000 to 920000 uploaded
✅ Rows 920000 to 940000 uploaded
✅ Rows 940000 to 960000 uploaded
✅ Rows 960000 to 980000 uploaded
✅ Rows 980000 to 1000000 uploaded
✅ Rows 1000000 to 1020000 uploaded
✅ Rows 1020000 to 1040000 uploaded
✅ Rows 1040000 to 1060000 uploaded
✅ Rows 1060000 to 1080000 uploaded
✅ Rows 1080000 to 1100000 uploaded
✅ Rows 1100000 to 1120000 uploaded
✅ Rows 1120000 to 1140000 uploaded
✅ Rows 1140000 to 1160000 uploaded
✅ Rows 1160000 to 1180000 uploaded
✅ Rows 1180000 to 1200000 uploaded
✅ Rows 1200000 to 1220000 uploaded
✅ Rows 1220000 to 1240000 uploaded
✅ Rows 1240000 to 1260000 uploaded
✅ Rows 1260000 to 1280000 uploaded
✅ Rows 1280000 to 1300000 uploaded
✅ Rows 1300000 to 1320000 uploaded
✅ Rows 1320000 to 1340000 uploaded
✅ Rows 1340000 to 1360000 uploaded
✅ Rows 1360000 to 1380000 uploaded
✅ Rows 1380000 to 1400000 uploaded
✅ Rows 1400000 to 1420000 uploaded
✅ Rows 1420000 to 1440000 uploaded
✅ Rows 1440000 to 1460000 uploaded
✅ Rows 1460000 to 1480000 uploaded
✅ Rows 1480000 to 1500000 uploaded
✅ Rows 1500000 to 1520000 uploaded
✅ Rows 1520000 to 1540000 uploaded
✅ Rows 1540000 to 1560000 uploaded
✅ Rows 1560000 to 1580000 uploaded
✅ Rows 1580000 to 1600000 uploaded
✅ Rows 1600000 to 1620000 uploaded
✅ Rows 1620000 to 1640000 uploaded
✅ Rows 1640000 to 1660000 uploaded
✅ Rows 1660000 to 1680000 uploaded
✅ Rows 1680000 to 1700000 uploaded
✅ Rows 1700000 to 1720000 uploaded
✅ Rows 1720000 to 1740000 uploaded
✅ Rows 1740000 to 1760000 uploaded
✅ Rows 1760000 to 1780000 uploaded
✅ Rows 1780000 to 1800000 uploaded
✅ Rows 1800000 to 1820000 uploaded
✅ Rows 1820000 to 1840000 uploaded
✅ Rows 1840000 to 1860000 uploaded
✅ Rows 1860000 to 1880000 uploaded
✅ Rows 1880000 to 1900000 uploaded
✅ Rows 1900000 to 1920000 uploaded
✅ Rows 1920000 to 1940000 uploaded
✅ Rows 1940000 to 1960000 uploaded
✅ Rows 1960000 to 1980000 uploaded
✅ Rows 1980000 to 2000000 uploaded
✅ Rows 2000000 to 2020000 uploaded
✅ Rows 2020000 to 2040000 uploaded
✅ Rows 2040000 to 2060000 uploaded
✅ Rows 2060000 to 2080000 uploaded
✅ Rows 2080000 to 2100000 uploaded
✅ Rows 2100000 to 2120000 uploaded
✅ Rows 2120000 to 2140000 uploaded
✅ Rows 2140000 to 2160000 uploaded
✅ Rows 2160000 to 2180000 uploaded
✅ Rows 2180000 to 2200000 uploaded
✅ Rows 2200000 to 2220000 uploaded
✅ Rows 2220000 to 2240000 uploaded
✅ Rows 2240000 to 2260000 uploaded
✅ Rows 2260000 to 2280000 uploaded
✅ Rows 2280000 to 2300000 uploaded
✅ Rows 2300000 to 2320000 uploaded
✅ Rows 2320000 to 2340000 uploaded
✅ Rows 2340000 to 2360000 uploaded
✅ Rows 2360000 to 2380000 uploaded
✅ Rows 2380000 to 2400000 uploaded
✅ Rows 2400000 to 2420000 uploaded
✅ Rows 2420000 to 2440000 uploaded
✅ Rows 2440000 to 2460000 uploaded
✅ Rows 2460000 to 2480000 uploaded
✅ Rows 2480000 to 2500000 uploaded
✅ Rows 2500000 to 2520000 uploaded
✅ Rows 2520000 to 2540000 uploaded
✅ Rows 2540000 to 2560000 uploaded
✅ Rows 2560000 to 2580000 uploaded
✅ Rows 2580000 to 2600000 uploaded
✅ Rows 2600000 to 2620000 uploaded
✅ Rows 2620000 to 2640000 uploaded
✅ Rows 2640000 to 2660000 uploaded
✅ Rows 2660000 to 2680000 uploaded
✅ Rows 2680000 to 2700000 uploaded
✅ Rows 2700000 to 2720000 uploaded
✅ Rows 2720000 to 2740000 uploaded
✅ Rows 2740000 to 2760000 uploaded
✅ Rows 2760000 to 2780000 uploaded
✅ Rows 2780000 to 2800000 uploaded
✅ Rows 2800000 to 2820000 uploaded
✅ Rows 2820000 to 2840000 uploaded
✅ Rows 2840000 to 2860000 uploaded
✅ Rows 2860000 to 2880000 uploaded
✅ Rows 2880000 to 2900000 uploaded
✅ Rows 2900000 to 2920000 uploaded
✅ Rows 2920000 to 2940000 uploaded
✅ Rows 2940000 to 2960000 uploaded
✅ Rows 2960000 to 2980000 uploaded
✅ Rows 2980000 to 3000000 uploaded
✅ Rows 3000000 to 3020000 uploaded
✅ Rows 3020000 to 3040000 uploaded
✅ Rows 3040000 to 3060000 uploaded
✅ Rows 3060000 to 3080000 uploaded
✅ Rows 3080000 to 3100000 uploaded
✅ Rows 3100000 to 3120000 uploaded
✅ Rows 3120000 to 3140000 uploaded
✅ Rows 3140000 to 3160000 uploaded
✅ Rows 3160000 to 3180000 uploaded
✅ Rows 3180000 to 3200000 uploaded
✅ Rows 3200000 to 3220000 uploaded
✅ Rows 3220000 to 3240000 uploaded
✅ Rows 3240000 to 3260000 uploaded
✅ Rows 3260000 to 3280000 uploaded
✅ Rows 3280000 to 3300000 uploaded
✅ Rows 3300000 to 3320000 uploaded
✅ Rows 3320000 to 3340000 uploaded
✅ Rows 3340000 to 3360000 uploaded
✅ Rows 3360000 to 3380000 uploaded
✅ Rows 3380000 to 3400000 uploaded
✅ Rows 3400000 to 3420000 uploaded
✅ Rows 3420000 to 3440000 uploaded
✅ Rows 3440000 to 3460000 uploaded
✅ Rows 3460000 to 3480000 uploaded
✅ Rows 3480000 to 3500000 uploaded
✅ Rows 3500000 to 3520000 uploaded
✅ Rows 3520000 to 3540000 uploaded
✅ Rows 3540000 to 3560000 uploaded
✅ Rows 3560000 to 3580000 uploaded
✅ Rows 3580000 to 3600000 uploaded
✅ Rows 3600000 to 3620000 uploaded
✅ Rows 3620000 to 3640000 uploaded
✅ Rows 3640000 to 3660000 uploaded
✅ Rows 3660000 to 3680000 uploaded
✅ Rows 3680000 to 3700000 uploaded
✅ Rows 3700000 to 3720000 uploaded
✅ Rows 3720000 to 3740000 uploaded
✅ Rows 3740000 to 3760000 uploaded
✅ Rows 3760000 to 3780000 uploaded
✅ Rows 3780000 to 3800000 uploaded
✅ Rows 3800000 to 3820000 uploaded
✅ Rows 3820000 to 3840000 uploaded
✅ Rows 3840000 to 3860000 uploaded
✅ Rows 3860000 to 3880000 uploaded
✅ Rows 3880000 to 3900000 uploaded
✅ Rows 3900000 to 3920000 uploaded
✅ Rows 4180000 to 4200000 uploaded
✅ Rows 4200000 to 4220000 uploaded
✅ Rows 4220000 to 4240000 uploaded
✅ Rows 4240000 to 4260000 uploaded
✅ Rows 4260000 to 4280000 uploaded
✅ Rows 4280000 to 4300000 uploaded
✅ Rows 4300000 to 4320000 uploaded
✅ Rows 4320000 to 4340000 uploaded
✅ Rows 4340000 to 4360000 uploaded
✅ Rows 4360000 to 4380000 uploaded
✅ Rows 4380000 to 4400000 uploaded
✅ Rows 4400000 to 4420000 uploaded
✅ Rows 4420000 to 4440000 uploaded
✅ Rows 4440000 to 4460000 uploaded
✅ Rows 4460000 to 4480000 uploaded
✅ Rows 4480000 to 4500000 uploaded
✅ Rows 4500000 to 4520000 uploaded
✅ Rows 4520000 to 4540000 uploaded
✅ Rows 4540000 to 4560000 uploaded
✅ Rows 4560000 to 4580000 uploaded
✅ Rows 4580000 to 4600000 uploaded
✅ Rows 4600000 to 4620000 uploaded
✅ Rows 4620000 to 4640000 uploaded
✅ Rows 4640000 to 4660000 uploaded
✅ Rows 4660000 to 4680000 uploaded
✅ Rows 4680000 to 4700000 uploaded
✅ Rows 4700000 to 4720000 uploaded
✅ Rows 4720000 to 4740000 uploaded
✅ Rows 4740000 to 4760000 uploaded
✅ Rows 4760000 to 4780000 uploaded
✅ Rows 4780000 to 4800000 uploaded
✅ Rows 4800000 to 4820000 uploaded
✅ Rows 4820000 to 4840000 uploaded
✅ Rows 4840000 to 4860000 uploaded
✅ Rows 4860000 to 4880000 uploaded
✅ Rows 4880000 to 4900000 uploaded
✅ Rows 4900000 to 4920000 uploaded
✅ Rows 4920000 to 4940000 uploaded
✅ Rows 4940000 to 4960000 uploaded
✅ Rows 4960000 to 4980000 uploaded
✅ Rows 4980000 to 5000000 uploaded
✅ Rows 5000000 to 5020000 uploaded
✅ Rows 5020000 to 5040000 uploaded
✅ Rows 5040000 to 5060000 uploaded
✅ Rows 5060000 to 5080000 uploaded
✅ Rows 5080000 to 5100000 uploaded
✅ Rows 5100000 to 5120000 uploaded
✅ Rows 5120000 to 5140000 uploaded
✅ Rows 5140000 to 5160000 uploaded
✅ Rows 5160000 to 5180000 uploaded
✅ Rows 5180000 to 5200000 uploaded
✅ Rows 5200000 to 5220000 uploaded
✅ Rows 5220000 to 5240000 uploaded
✅ Rows 5240000 to 5260000 uploaded
✅ Rows 5260000 to 5280000 uploaded
✅ Rows 5280000 to 5300000 uploaded
✅ Rows 5300000 to 5320000 uploaded
✅ Rows 5320000 to 5340000 uploaded
✅ Rows 5340000 to 5360000 uploaded
✅ Rows 5360000 to 5380000 uploaded
✅ Rows 5380000 to 5400000 uploaded
✅ Rows 5400000 to 5420000 uploaded
✅ Rows 5420000 to 5440000 uploaded
✅ Rows 5440000 to 5460000 uploaded
✅ Rows 5460000 to 5480000 uploaded
✅ Rows 5480000 to 5500000 uploaded
✅ Rows 5500000 to 5520000 uploaded
✅ Rows 5520000 to 5540000 uploaded
✅ Rows 5540000 to 5560000 uploaded
✅ Rows 5560000 to 5580000 uploaded
✅ Rows 5580000 to 5600000 uploaded
✅ Rows 5600000 to 5620000 uploaded
✅ Rows 5620000 to 5640000 uploaded
✅ Rows 5640000 to 5660000 uploaded
✅ Rows 5660000 to 5680000 uploaded
✅ Rows 5680000 to 5700000 uploaded
✅ Rows 5700000 to 5720000 uploaded
✅ Rows 5720000 to 5740000 uploaded
✅ Rows 5740000 to 5760000 uploaded
✅ Rows 5760000 to 5780000 uploaded
✅ Rows 5780000 to 5800000 uploaded
✅ Rows 5800000 to 5820000 uploaded
✅ Rows 5820000 to 5840000 uploaded
✅ Rows 5840000 to 5860000 uploaded
✅ Rows 5860000 to 5880000 uploaded
✅ Rows 5880000 to 5900000 uploaded
✅ Rows 5900000 to 5920000 uploaded
✅ Rows 5920000 to 5940000 uploaded
✅ Rows 5940000 to 5960000 uploaded
✅ Rows 5960000 to 5980000 uploaded
✅ Rows 5980000 to 6000000 uploaded
✅ Rows 6000000 to 6020000 uploaded
✅ Rows 6020000 to 6040000 uploaded
✅ Rows 6040000 to 6060000 uploaded
✅ Rows 6060000 to 6080000 uploaded
✅ Rows 6080000 to 6100000 uploaded
✅ Rows 6100000 to 6120000 uploaded
✅ Rows 6120000 to 6140000 uploaded
✅ Rows 6140000 to 6160000 uploaded
✅ Rows 6160000 to 6180000 uploaded
✅ Rows 6180000 to 6200000 uploaded
✅ Rows 6200000 to 6220000 uploaded
✅ Rows 6220000 to 6240000 uploaded
✅ Rows 6240000 to 6260000 uploaded
✅ Rows 6260000 to 6280000 uploaded
✅ Rows 6280000 to 6300000 uploaded
✅ Rows 6300000 to 6320000 uploaded
✅ Rows 6320000 to 6340000 uploaded
✅ Rows 6340000 to 6360000 uploaded
✅ Rows 6360000 to 6380000 uploaded
✅ Rows 6380000 to 6400000 uploaded
✅ Rows 6400000 to 6420000 uploaded
✅ Rows 6420000 to 6440000 uploaded
✅ Rows 6440000 to 6460000 uploaded
✅ Rows 6460000 to 6480000 uploaded
✅ Rows 6480000 to 6500000 uploaded
✅ Rows 6500000 to 6520000 uploaded
✅ Rows 6520000 to 6540000 uploaded
✅ Rows 6540000 to 6560000 uploaded
✅ Rows 6560000 to 6580000 uploaded
✅ Rows 6580000 to 6600000 uploaded
✅ Rows 6600000 to 6620000 uploaded
✅ Rows 6620000 to 6640000 uploaded
✅ Rows 6640000 to 6660000 uploaded
✅ Rows 6660000 to 6680000 uploaded
✅ Rows 6680000 to 6700000 uploaded
✅ Rows 6700000 to 6720000 uploaded
✅ Rows 6720000 to 6740000 uploaded
✅ Rows 6740000 to 6760000 uploaded
✅ Rows 6760000 to 6780000 uploaded
✅ Rows 6780000 to 6800000 uploaded
✅ Rows 6800000 to 6820000 uploaded
✅ Rows 6820000 to 6840000 uploaded
✅ Rows 6840000 to 6860000 uploaded
✅ Rows 6860000 to 6880000 uploaded
✅ Rows 6880000 to 6900000 uploaded
✅ Rows 6900000 to 6920000 uploaded
✅ Rows 6920000 to 6940000 uploaded
✅ Rows 6940000 to 6960000 uploaded
✅ Rows 6960000 to 6980000 uploaded
✅ Rows 6980000 to 7000000 uploaded

In [37]:
upload_dataframe_in_chunks(business_categories, 'business_categories')

Uploading 150346 rows to 'business_categories' in chunks of 20000...
✅ Rows 0 to 20000 uploaded
✅ Rows 20000 to 40000 uploaded
✅ Rows 40000 to 60000 uploaded
✅ Rows 60000 to 80000 uploaded
✅ Rows 80000 to 100000 uploaded
✅ Rows 100000 to 120000 uploaded
✅ Rows 120000 to 140000 uploaded
✅ Rows 140000 to 160000 uploaded